### ISSUE TITLE
select vs update

### ISSUE THREAD

**Issue by mahmutoktay** [jamesbontempo/njodb#17]
`async function main() {

    const sonuc = await kanalDB.select(
        record => record.ad === "SOMETHING"
    );
    //console.log(sonuc.data.length);

    if(1 === 1){
        const upd = await kanalDB.update(
            record => record.name === "asdfasdf",
            record => { 
                record.surname = "babas"; 
                return record; 
            }
        )
    
        console.log(upd.updated);
    }
}

main();`

select and update distribution works separately. But when updating after the selection amount, the update function does not work.

**Comment by jamesbontempo** [comment]
Hi @mahmutoktay! Can you tell me what version you're using?

**Comment by mahmutoktay** [comment]
Thanks for interest. The database I've wanted for a long time. I like it a lot. but I couldn't get past this error
"dependencies": {
    "njodb": "^0.4.36"
  }

**Comment by jamesbontempo** [comment]
I'm glad to know that you think `njodb` could be very helpful!

There is a full test suite for the package, and I always ensure that all tests pass before publishing a new version, but I went ahead and created a simple project to do some additional tests. I created a basic skeleton using `npm init` and its default values, then installed the latest version of `njodb` (0.4.36) from npm (`npm install njodb`).

Then I wrote this very simple script with a bunch of console logging to check results along the way:
```
const njodb = require("njodb");

const main = async () => {
    const db = new njodb.Database();

    const i = await db.insert([
        {id: 1, name: "a"},
        {id: 2, name: "b"},
        {id: 3, name: "c"},
    ]);
    console.log("Inserted:", i.inserted);

    const s1 = await db.select(
        (record) => record.id === 1
    );
    console.log("Selected:", s1.selected);
    console.log(s1.data);

    const u2 = await db.update(
        (record) => record.id === 2,
        (record) => { record.name = "d"; return record; }
    );
    console.log("Updated:", u2.updated);

    const s2 = await db.select(
        (record) => record.id === 2
    );
    console.log("Selected:", s2.selected);
    console.log(s2.data);

    const d3 = await db.delete(
        (record) => record.id === 3
    );
    console.log("Deleted:", d3.deleted);

    const s3 = await db.select(
        (record) => record.id === 3
    );
    console.log("Selected:", s3.selected);
    console.log(s3.data);

    await db.drop();
}

main();
```

Running the script produced the following output showing that everything worked as expected:
```
Inserted: 3
Selected: 1
[ { id: 1, name: 'a' } ]
Updated: 1
Selected: 1
[ { id: 2, name: 'd' } ]
Deleted: 1
Selected: 0
[]
```
It's difficult to troubleshoot your exact situation because I do not have your data and full code, but can you try running the simple script I created and seeing if it works as expected?

**Comment by mahmutoktay** [comment]
I examined your codes in detail and got exactly the same results in the applications. But I cannot provide the same things with my own data. I actually have no idea where it is. Where am I making the mistake? I leave the codes and database here. Thank you very much for your interest.
[testnjodb.zip](https://github.com/jamesbontempo/njodb/files/14859390/testnjodb.zip)

**Comment by jamesbontempo** [comment]
Hi @mahmutoktay :)

I just published a new version (0.4.37) that has a change I think might address the issue. Can you upgrade, test it out again, and let me know if it works?

Thanks!

**Comment by mahmutoktay** [comment]
It worked perfectly. Thank you so much for everything

**Comment by jamesbontempo** [comment]
Glad to hear it! Let me know if you run into any other issues :)
