### ISSUE TITLE
Adding single Object into new Store triggers Exception

### ISSUE THREAD

**Issue by quiqueck** [jamesbontempo/njodb#2]
Minimal Example:

```JavaScript
const njodb = require('njodb')
const db = new njodb.Database(this.path)
db.insert([{value:0}]).then(() => {})
```

Error:
> TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Array
>     at Object.writeFile (node:fs:1475:5)
>     at appendFile (node:fs:1538:6)
>     at node:internal/util:297:30
>     at new Promise (<anonymous>)
>     at appendFile (node:internal/util:296:12)
>     at insertStoreData (./node_modules/njodb/lib/njodb.js:337:32)
>     at async Promise.all (index 2)
>     at Database.insert ./node_modules/njodb/index.js:264:25)

I believe the error is due to `records[i]`beeing initialized as an empty array in `Database.insert`. 
```
for (let i = 0; i < this.properties.datastores; i++) {
    records[i] = [];
}
```

As far as I understood the code those should be initialized as empty strings instead.

**Comment by jamesbontempo** [comment]
Hi there @quiqueck. Thanks for finding that issue! Oddly, I wasn't able to replicate it exactly, but I _did_ get a related error. Either way I'm going to commit your PR, and then fix the same issue w/the synchronous version of the method, too. And maybe also add some logic to simply skip items that are blank strings, rather than making an unnecessary appendFile call...
