### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by ekoeryanto** [jamesbontempo/njodb#7]

**Comment by jamesbontempo** [comment]
Hello @ekoeryanto :) Thanks for the suggestion! I'm curious, do you have a use case for Typescript support or do you just think it's a good idea? –James

**Comment by ekoeryanto** [comment]
I installed and it blocked me to use this, as i am a lazy developer with power of typescript intelisense.
😉

**Comment by jamesbontempo** [comment]
Oh, I see: the "lazy developer" use case 😂 Are you trying to use it in a professional production environment of some sort or just doing some personal experimenting?

**Comment by paradis-A** [comment]
i just created a declaration file for it. will try to make pr

**Comment by jamesbontempo** [comment]
Thanks for making the declaration file @paradis-A! Honestly, I don't have any experience with TypeScript & don't know how to test your work, but I did a quick review & everything looks pretty straightforward. And if these updates are allowing you to use the library in a TypeScript environment, then I guess that's all we need :) I'm going to merge your PR in a minute, then do some quick version bumps 👍

**Comment by paradis-A** [comment]
> 

You're welcome :). I should have done this earlier but life got busy, It's just a declaration file which the code editor will know what hint to provide so it's more efficient even for those who doesn't know typescript. Thanks to your well detailed documentation it was more easy to make declaration file since you  specified what to are the params and return values briefly, Sometimes lazy people like me scratch our head as if was full of dandruff when we started typing ".", people just love exploring and it was wonderful when we press dot and it gives a short detail and a hint which is copy from the readme. I have to make another pr again there are some arguments that I have to turn as optional or typescript dev like have to scratch out dandruffs XD.

**Comment by jamesbontempo** [comment]
Glad you were able to get rid of some of the dandruff :P I'll keep my eye out for the next PR...
